LEVEL_MAP = [
	'                            XXXXXXXXXXXXXXXXXXXXXXXXXXX',
	'                            XXXXXXXXXXXXXXXXXXXXXXXXXXX',
	'         X                  XXXXXXXXXXXXXXXXXXXXXXXXXXX',
	'       XXXX           XX    XXXXXXXXXXXXXXXXXXXXXXXXXXX',
	'   P                        XXXXXXXXXXXXXXXXXXXXXXXXXXX',
	'XXXXX         XX         XX XXXXXXXXXXXXXXXXXXXXXXXXXXX',
	' XXXX       XX X            XXXXXXXXXXXXXXXXXXXXXXXXXXX',
	' XX    X  XXXX    XX  XX          XXXXXXXXXXXXXXXXXXXXX',
	'       X  XXXX    XX  XXX           XXXXXXXXXXXXXXXXXXX',
	' X  XXXX  XXXXXX  XX  XXXX  XXXXXX                     ',
	'XXXXXXXXX XXXXXX  XX  XXXX  XXXXXX                     ',
	'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
]

TILE_SIZE = 32
SCREEN_WIDTH = 1366
SCREEN_HEIGHT = 768

# colors 
BG_COLOR = '#060C17'
PLAYER_COLOR = '#C4F7FF'
TILE_COLOR = '#94D7F2'

# camera
#CAMERA_BORDERS = {
#	'left': 100,
#	'right': 200,
#	'top': 100,
#	'bottom': 150
#}

CAMERA_BORDERS = {
	'left': 50,
	'right': 100,
	'top': 50,
	'bottom': 75
}
